extends: 'eslint-config-wikimedia'

parserOptions:
  ecmaVersion: 10

env:
  node: true

rules:
  indent:
    - error
    - 4
    - SwitchCase: 1
      MemberExpression: off
  space-in-parens: [error, never]
  no-multi-spaces: off
  no-multiple-empty-lines: off
  one-var: off
  array-bracket-spacing: off
  computed-property-spacing: off
  no-unused-vars: [error, {args: none}]
  no-underscore-dangle: off
  comma-dangle: off
  camelcase: off
  key-spacing: off
  space-before-function-paren: off
  quote-props: off
  operator-linebreak: off
  max-statements-per-line: off
  brace-style: off
